### ISSUE TITLE
Fork Project don’t syncs Issues 

### ISSUE THREAD

**Issue by oleksis** [Zaubeerer/github_board_tutorial#21]
In the article on PyBites you say:

> If you don't want to create those issues yourself, you might also want to fork the github_board_tutorial that I created for the purpose of this article. Your issue list might look like the following:

And when I fork you Project my project have 0 Issues.

My question is: How I do Fork and syncing 
my Issues with your project issues?

**Comment by Zaubeerer** [comment]
Dear @oleksis, 

I am sorry to hear that, I was not aware of this problem.

On GitLab, I would export the repository for you, such that you can import it with the issues.

However, GitHub does not allow to simply export projects as far as I know, so you will have to implement the issues on your own. 

However, it just took me 5 min to do that and you, of course, don't need to add as many issues.

Cheers! 

Robin
